name: Generate Datapack
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout (only last commit)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get KiCad project name
      run: echo "PROJECT_NAME=$(basename *.kicad_pro .kicad_pro)" >> $GITHUB_ENV

    - name: Clone and Checkout our KiBot config
      uses: actions/checkout@v4
      with:
        repository: Cimos/kibot-config
        path: ./kibot-config
        ref: main

    - name: Build Datapack
      uses: Cimos/kibot-config@1-add-penalization-to-build
      with:
        config: kibot-config/build.kibot.yaml
        dir: output
        schema: '${{ env.PROJECT_NAME }}.kicad_sch'
        board: '${{ env.PROJECT_NAME }}.kicad_pcb'
        logfile: 'logfile.log'
        # verbose: 2

    - name: Upload logfile
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-lofile
        path: logfile
      
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-datapack
        path: output
