name: Generate Datapack
on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
    - name: Checkout (only last commit)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get KiCad project name
      run: echo "PROJECT_NAME=$(basename *.kicad_pro .kicad_pro)" >> $GITHUB_ENV

    - name: Clone and Checkout our KiBot config
      uses: actions/checkout@v4
      with:
        repository: Cimos/kibot-config
        path: ./kibot-config
        ref: main

    - name: Build Datapack
      uses: Cimos/kibot-config@main
      with:
        config: kibot-config/build.kibot.yaml
        dir: output
        schema: '${{ env.PROJECT_NAME }}.kicad_sch'
        board: '${{ env.PROJECT_NAME }}.kicad_pcb'
        logfile: 'logfile/logfile.log'
        # verbose: 2

    - name: Upload logfile
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-logfile
        path: logfile
      
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-datapack
        path: output
